---
apiVersion: v1
kind: Service
metadata:
  name: wildfly
spec:
  type: NodePort
  selector:
    app: wildfly
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: management
      port: 9990
      targetPort: 9990
      nodePort: 30090